README.md, automaxprocs.go, automaxprocs_test.go, example_test.go, maxprocs/example_test.go, maxprocs/maxprocs.go, maxprocs/maxprocs_test.go
The current package API is both rigid and difficult to test; in general,
we should avoid exposing complex functionality *only* via import-time
side-effects.
This PR refactors the package API to be more testable and flexible, and
then adds a code sample to the README, some testable examples, and
enough tests to get 100% coverage on the main package.
(I'll follow up with a diff to our internal version of this package;
this API should allow us to make that change fully backward-compatible.)
=> Make exported API more flexible

Makefile, glide.lock, glide.yaml, maxprocs/maxprocs_test.go
In order to test the `maxprocs` package, we need to control the value of
`$GOMAXPROCS`. Unfortunately, Travis sets `$GOMAXPROCS` in every
container.
To work around this, use `TestMain` to unset `$GOMAXPROCS` for the
`maxprocs` package tests, restoring the previous value after tests
complete.
=> Unset $GOMAXPROCS during tests

CHANGELOG.md, maxprocs/version.go
Preparation for initial release.
Note that we can't usefully put `version.go` into the main `automaxprocs` package, since that package has import-time side-effects.
=> Prepare for v1.0.0

maxprocs/maxprocs.go
We're currently logging the current GOMAXPROCS rather than the value
determined using the CPU quota, which leads to a very confusing message
on startup.
=> Log value of GOMAXPROCS that we're about to set

maxprocs/maxprocs.go, maxprocs/maxprocs_test.go
Currently, we call `GOMAXPROCS` even if we are unable to determine the
CPU quota. Since the returned value is 0, this doesn't have an impact,
but avoid calling `runtime.GOMAXPROCS` to set the value unless we
successfully determine the quota.
Improve logging so users have clear messaging about the source of logs
(maxprocs) and what is being changed (are we ignoring, updating, etc)
and make all the messages more consistent.
=> Refactor maxprocs: better logging and only set on success

automaxprocs.go, example_test.go
In order to render a whole-file example, we need at least one
package-level declaration.
=> Fix example rendering

internal/runtime/runtime.go, maxprocs/maxprocs.go, maxprocs/maxprocs_test.go
We previously set the minimum GOMAXPROCS value to 2 as that was the
minimum allocation we expected internally. However, if the allocation is
actually smaller, we should use lower GOMAXPROCS.
This will also allow us to reduce the allocation size and use a more
appropriate GOMAXPROCS which will reduce the amount of CFS throttling.
=> Minimum GOMAXPROCS should be 1

CHANGELOG.md, internal/runtime/cpu_quota_linux.go
Apologies, this was an oversight on my part back when we wrote the `x/runtime` precursor that I helped to review. I'd since been working on the (it turns out false) assumption that this had been floor all along. Recent investigation into pervasive low-grade throttling tho led me to this discovery.
In short:
- as far as the Go scheduler is concerned, there's no such thing as a fractional CPU
- so let's say you have your quota set to `N + p` for some integer `N` and some `0.0 < p < 1.0`
- the only safe assumption then is that you're using that `p` value as a hedge for something like "systems effects" or "c libraries"
- in that latter case, what you really might want to be able give maxprocs some value `K` of reserved CPUs for some parasite like a C library or sidecar; but that's probably …
=> Use floor(quota) rather than ceil(quota)

maxprocs/maxprocs.go
Rather than specifying the type in the format, we can rely on the
default formatting using "%v".
Fixes #15.
=> Fix "%d" being used with strings

CHANGELOG.md, maxprocs/version.go
This releases v1.3.0 of automaxprocs. The only change in this release is
the migration to Go modules.
=> Preparing release v1.3.0

internal/cgroups/subsys.go, internal/cgroups/subsys_test.go
cgroup sub system names can contain colons which is also used as separator symbol, e.g.:
```
12:cpu,cpuacct:/system.slice/containerd.service/kubepods-besteffort-podb41662f7_b03a_4c65_8ef9_6e4e55c3cf27.slice:cri-containerd:1753b7cbbf62734d812936961224d5bc0cf8f45214e0d5cdd1a781a053e7c48f
```
=> Fix cgroup sub system parsing with names containing colons

.github/workflows/go.yml, internal/cgroups/cgroup.go, internal/cgroups/cgroup_test.go, internal/cgroups/cgroups.go, internal/cgroups/cgroups_test.go, internal/cgroups/errors.go, internal/cgroups/mountpoint.go, internal/cgroups/mountpoint_test.go, internal/cgroups/subsys.go, internal/cgroups/subsys_test.go, internal/cgroups/util_test.go, internal/runtime/cpu_quota_linux.go, internal/runtime/cpu_quota_unsupported.go, tools/tools.go
Run gofmt on everything to add `//go:build` tags.
=> ci: Test with Go 1.16/1.17, lint on 1.17

CHANGELOG.md, maxprocs/version.go
Release v1.5.0 with support for cgroups2.
In addition to the tests, I've deployed this change to a staging machine
internally to verify that it doesn't break cgroups v1 for us.
Refs GO-1322
=> Prepare release v1.5.0

README.md
This diff adds a single benchmark from the: https://github.com/uber-go/automaxprocs/issues/12#issuecomment-569327824
=> README: add a benchmark

internal/cgroups/cgroups2.go
Fixes a leak with the file descriptor within the cgroups v2 functionality.
=> defer close cpuMaxParams to fix leak

CHANGELOG.md, maxprocs/version.go
Commits in this release:
* e1c1306 - (origin/master, origin/HEAD, master) Test against Go 1.20 (5 hours ago) <Albert Wang>
* 77a1338 - CI: upgrade staticcheck to v2023.1.2 to make test pass, Add go1.19 (2 weeks ago) <shvc>
* abb2d82 - Bump golang.org/x/sys in /tools (#60) (3 weeks ago) <dependabot[bot]>
* 58f5aee - typo fix in runtime.go (3 months ago) <yutaroyamanaka>
*   db7cbd0 - Merge pull request #57 from rphillips/fix_leak (3 months ago) <Sung Yoon Whang>
|\
| * 1759cfc - defer close cpuMaxParams to fix leak (7 months ago) <Ryan Phillips>
|/
* 0b356b1 - Upgrade to yaml.v3 3.0.1 (#55) (10 months ago) <Abhinav Gupta>
* d835ace - Support child control cgroups in cgroupsv2 (#53) (11 months ago) <Maciej Biłas>
* ce572da - README: add performance section (#52) (11 months ago) <Alexey …
=> Release v1.5.2

internal/cgroups/mountpoint.go, internal/cgroups/mountpoint_test.go
Fix the parsing of mountinfo when super options has fields with spaces in, which is the case on WSL as it includes `path=C:\\Program Files\...`.
Fixes #72
=> fix: mountinfo parsing

CHANGELOG.md
Bug fixes on top of v1.5.2. Fixes for division by zero and mountinfo parsing.
=> Release v1.5.3

.github/workflows/go.yml, go.mod, tools/go.mod
This updates go.mod files to use Go 1.21.
It also updates the CI to use Go 1.20 and Go 1.21 to test.
Note that this specifies the minimum version required to work with automaxprocs to be Go 1.20 as specified in the toolchain specification (https://go.dev/doc/toolchain).
=> Use Go 1.21

internal/runtime/cpu_quota_linux.go, internal/runtime/cpu_quota_linux_test.go, internal/runtime/cpu_quota_unsupported.go, internal/runtime/runtime.go, maxprocs/maxprocs.go, maxprocs/maxprocs_test.go
Add a `RoundQuotaFunc` option to control how the CPU quota should be rounded. The default is still rounding down (floor).
This is related to issue https://github.com/uber-go/automaxprocs/issues/78
=> Add option to round up CPU quota

glide.yaml
We've longed moved away to go.mod and install using glide is no longer
supported. Remove glide.yaml file to clean up unused files.
=> Remove glide.yaml
